# Generated by Django 4.1 on 2022-11-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname1', models.CharField(max_length=20)),
                ('lastname1', models.CharField(max_length=20)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=5)),
                ('desc', models.TextField(default='This is description', max_length=700)),
                ('is_true', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=5)),
                ('desc', models.TextField(default='This is description', max_length=700)),
                ('is_true', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True)),
                ('surname', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donate_to', models.CharField(choices=[('ka', 'Kabul'), ('He', 'Helmand'), ('Ba', 'Badakhshan'), ('Pa', 'Panjsher'), ('Gh', 'Ghazni')], default=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categories', models.CharField(choices=[('el', 'Electronic'), ('gr', 'Groceries'), ('tr', 'Transportion')], default=True, max_length=12)),
                ('is_available', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(default='This is description', max_length=500)),
                ('create', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
